---
- name: "Install Mysql"
  apt:
    name:
      - python-mysqldb
      - mysql-server
    state: present

- name: "Start MySQL"
  service:
    name: mysql
    state: started
    enabled: yes

- name: Remove the MySQL test database.
  mysql_db:
    db: test
    state: absent
- name: "Create a MySQL database for Drupal."
  mysql_db:
    db: "{{ domain }}"
    state: present
- name: "Create a MySQL user for Drupal."
  mysql_user:
    name: "{{ domain }}"
    password: "1234"
    priv: "{{ domain }}.*:ALL"
    host: localhost
    state: present

    
